In [2]:
import numpy as np
from scipy import stats

In [9]:
rent_prices = np.array([1200, 1350, 1200, 1400, 1550, 1300, 1200, 12000])

In [10]:
#Calculating Central Tendency
mean_rent = np.mean(rent_prices)
median_rent = np.median(rent_prices)

In [11]:
mode_result = stats.mode(rent_prices, keepdims = True)
print(mode_result)
mode_rent = mode_result.mode[0]
mode_count = mode_result.count[0]

ModeResult(mode=array([1200]), count=array([3]))


In [12]:
print(f"Mean Rent: ${mean_rent:.2f}")
print(f"Median Rent: ${median_rent:.2f}")
print(f"Mode Rent: ${mode_rent} (Appers: {mode_count} times)")

Mean Rent: $2650.00
Median Rent: $1325.00
Mode Rent: $1200 (Appers: 3 times)


In [18]:
city_a_temps = np.array([24, 25, 26, 25, 25])
city_b_temps = np.array([10, 40, 5, 45, 25])

In [19]:
#Calculate Variance
var_a = np.var(city_a_temps)
var_b = np.var(city_b_temps)

In [21]:
#Calculate Standard Deviation
std_a = np.std(city_a_temps)
std_b = np.std(city_b_temps)

In [23]:
print(f"City A: Variance = {var_a:.2f} | Standard Deviation = {std_a:.2f}")
print(f"City B: Variance = {var_b:.2f} | Standard Deviation = {std_b:.2f}")

City A: Variance = 0.40 | Standard Deviation = 0.63
City B: Variance = 250.00 | Standard Deviation = 15.81


In [24]:
#Variables: Marketing Spend($), Online Sales($), and Store Complaints(Count)
marketing_spend = np.array([10, 20, 30, 40, 50])
online_sales = np.array([25, 45, 55, 75, 95])
complaints = np.array([15, 12, 10, 4, 2])

In [30]:
#Calculate Covariance Matrix between Spend and Sales, Spend and Complaints
cov_matrix = np.cov(marketing_spend, online_sales)
cov_matrix1 = np.cov(marketing_spend, complaints)

print(cov_matrix)
print(cov_matrix1)

[[250. 425.]
 [425. 730.]]
[[250.  -85. ]
 [-85.   29.8]]


In [42]:
#Calculate Correlation Coefficient Matrix
corr_matrix_positive = np.corrcoef(marketing_spend, online_sales)
corr_matrix_negative = np.corrcoef(marketing_spend, complaints)

In [43]:
correlation_spend_sales = corr_matrix_positive[0, 1]
correlation_spend_complaints = corr_matrix_negative[0, 1]

In [48]:
print(f"Covariance between Spend & Sales:\n{cov_matrix}\n")
print(f"Correlation of Spend and Sales \n {corr_matrix_positive}")
print(f"\nCorrelation of Spend and Complaints \n {corr_matrix_negative}\n")
print(f"Correlation (Spend vs Sales): {correlation_spend_sales:.4f} (Strong Positive)\n")
print(f"Correlation (Spend vs. Complaints): {correlation_spend_complaints:.4f}(Strong Negative)")

Covariance between Spend & Sales:
[[250. 425.]
 [425. 730.]]

Correlation of Spend and Sales 
 [[1.         0.99484975]
 [0.99484975 1.        ]]

Correlation of Spend and Complaints 
 [[ 1.         -0.98478356]
 [-0.98478356  1.        ]]

Correlation (Spend vs Sales): 0.9948 (Strong Positive)

Correlation (Spend vs. Complaints): -0.9848(Strong Negative)
